baseURL = "https://jmatth.com/"
languageCode = "en-us"
theme = "coder"
title = "jmatth"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Josh Matthews"
    info = "Professional Computer Toucher"
    description = "Josh's personal website"
    keywords = "developer,personal"
    avatarurl = "https://avatars3.githubusercontent.com/u/1316184"
    avatartitle = "I'm the one on the left."

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    # footercontent = "In the picture, I'm the one on the left."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase fa-2x"
    weight = 1
    url = "https://keybase.io/jmatth/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/jmatth/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter fa-2x"
#     weight = 3
#     url = "https://twitter.com/jmatth92/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
# [[menu.main]]
#     name = "Blog"
#     weight = 2
#     url  = "/posts/"
